<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
	<!-- NuGet Package Info -->
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>SpecMetrix.DataService</PackageId>
	<Version>0.1.12</Version>
	<Authors>Jason Jelks</Authors>
	<Company>SpecMetrix</Company>
	<Description>SpecMetrix DataServices</Description>
	<PackageTags>specmetrix data service mongodb</PackageTags>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

	<RepositoryUrl>https://github.com/Jason-Jelks/SpecMetrixLog/tree/main/SpecMetrixDataService</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SpecMetrix.Interfaces">
      <HintPath>..\..\Interfaces\SpecMetrixInterfaces\SpecMetrix.Interfaces\bin\Release\net10.0\SpecMetrix.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="SpecMetrix.Shared">
      <HintPath>..\..\Shared\SpecMetrixShared\SpecMetrix.Shared\bin\Release\net10.0\SpecMetrix.Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
